### ISSUE TITLE
script perform different accuracy than reported in the paper

### ISSUE THREAD

**Issue by tryerrorman** [ddtm/caffe#11]
I think you conduct a very good work. But when I reproduce the results, I come across some confusion. The results is very different from the results in your paper.
The results I reproduce are list below:
![image](https://user-images.githubusercontent.com/10434436/27680533-9f5590b4-5cee-11e7-9426-47ce7bfd77ba.png)
the paper reports results as 
![image](https://user-images.githubusercontent.com/10434436/27679819-6d2116a6-5cec-11e7-9f86-afdb0acbfbcb.png)
The reproduced amazon_to_webcam result is higher than that in the paper, while the other two goes the opposite direction.
If the parameter setting in the script is different from that used in the paper? How can I change it?

**Comment by tryerrorman** [comment]
I am sorry for confuse the test loss with the accuracy. I directly use the parse_log.sh provided in caffe which is not suite for this project.

**Comment by eddielyc** [comment]
when i reproduce amazon_to_webcam experiment, why the lp accuracy always stay low  (about 0.6)... All of my settings are default. Can you help me, plz
