### ISSUE TITLE
example failing in cpu mode

### ISSUE THREAD

**Issue by pseyfert** [ddtm/caffe#2]
I followed the instructions in README.md to run the example.
I downloaded the example data from https://drive.google.com/file/d/0B4IapRTv9pJ1WGZVd1VDMmhwdlE/view?pli=1
and included `CPU_ONLY := 1` in Makefile.config.
After executing `./examples/adaptation/scripts/prepare_experiments.sh <path>`,
I removed the gpu setting from `./examples/adaptation/experiments/amazon_to_webcam/scripts/train.sh` and switched to `solver_mode: CPU` in `examples/adaptation/experiments/amazon_
to_webcam/protos/solver.prototxt`.
executing the training script, I receive an error message and the program is aborted:

> F0804 16:37:13.917794 21538 db.hpp:116] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
> **\* Check failure stack trace: ***
>    @     0x7f2471d52778  (unknown)
>    @     0x7f2471d526b2  (unknown)
>    @     0x7f2471d520b4  (unknown)
>    @     0x7f2471d55055  (unknown)
>    @     0x7f24720b735e  caffe::db::LMDB::Open()
>    @     0x7f24720eed02  caffe::DataLayer<>::DataLayerSetUp()
>    @     0x7f24720d4402  caffe::BaseDataLayer<>::LayerSetUp()
>    @     0x7f24720d44f9  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
>    @     0x7f247216b240  caffe::Net<>::Init()
>    @     0x7f247216c2f5  caffe::Net<>::Net()
>    @     0x7f247208f82f  caffe::Solver<>::InitTrainNet()
>    @     0x7f24720909b0  caffe::Solver<>::Init()
>    @     0x7f2472090b86  caffe::Solver<>::Solver()
>    @           0x40d9b0  caffe::GetSolver<>()
>    @           0x406e12  train()
>    @           0x4047b7  main
>    @     0x7f246e58cb45  (unknown)
>    @           0x404dd0  (unknown)
>    @              (nil)  (unknown)
> Aborted

(running on debian jessie)

**Comment by ddtm** [comment]
Apparently, this error is not connected to GPU but rather to the location of your training data. I suspect that the training lmdbs were not successfully generated.

**Comment by pseyfert** [comment]
argh, indeed, thanks for the pointer. since there was no error from the preparation script, I asumed it went through fine. I now removed the redirection of the outputs in the script to /dev/null and fight through the erros (the first few were related to my system).
